{
 "title": "TSN_Demo",
 "time": { "from": "2020-09-30T15:39:54.744Z", "to": "2020-09-30T15:41:39.605Z" },
 "panels": [
  {
   "title": "Main Output Variables Hardware Status",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "Main Output Variables",
     "query": "SELECT \"Emergency Stop activated\", \"Machine on\", \"Spindle enabled\", \"Spindlebrake\", \"X-Axis enabled\", \"Y-Axis enabled\", \"Z-Axis enabled\" FROM \"Main Output Variables\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Emergency Stop activated" ], "type": "field" }
      ],
      [
       { "params": [ "Machine on" ], "type": "field" }
      ],
      [
       { "params": [ "Spindle enabled" ], "type": "field" }
      ],
      [
       { "params": [ "Spindlebrake" ], "type": "field" }
      ],
      [
       { "params": [ "X-Axis enabled" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Axis enabled" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis enabled" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Main Input Variables Hardware Status",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "measurement": "Main Input Variables",
     "select": [
      [
       { "params": [ "X-Axis faulty" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Axis faulty" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis faulty" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Additional Output Variables Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "Additional Output Variables",
     "query": "SELECT \"Current Line Number\", \"Mode\", \"Tool Number\", \"Uptime\", \"X-Axis at home\", \"X-Axis at neg Endstop\", \"X-Axis at pos Endstop\", \"Y-Axis at home\", \"Y-Axis at neg Endstop\", \"Y-Axis at pos Endstop\", \"Z-Axis at home\", \"Z-Axis at neg Endstop\", \"Z-Axis at pos Endstop\", \"Z-Axis at pos Endstop\" FROM \"Additional Output Variables\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Current Line Number" ], "type": "field" }
      ],
      [
       { "params": [ "Mode" ], "type": "field" }
      ],
      [
       { "params": [ "Tool Number" ], "type": "field" }
      ],
      [
       { "params": [ "Uptime" ], "type": "field" }
      ],
      [
       { "params": [ "X-Axis at home" ], "type": "field" }
      ],
      [
       { "params": [ "X-Axis at neg Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "X-Axis at pos Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Axis at home" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Axis at neg Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Axis at pos Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis at home" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis at neg Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis at pos Endstop" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Axis at pos Endstop" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Main Outpus Variables",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Main Output Variables",
     "query": "SELECT \"Spindlespeed Setpoint\", \"X-Velocity Setpoint\" FROM \"Main Output Variables\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Spindlespeed Setpoint" ], "type": "field" }
      ],
      [
       { "params": [ "X-Velocity Setpoint" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Velocity Setpoint" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Velocity Setpoint" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Additional Output Variables",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Additional Output Variables",
     "query": "SELECT \"Feedrate override\", \"Feedrate planned\", \"X-Position Setpoint\", \"Y-Position Setpoint\", \"Z-Position Setpoint\" FROM \"Additional Output Variables\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Feedrate override" ], "type": "field" }
      ],
      [
       { "params": [ "Feedrate planned" ], "type": "field" }
      ],
      [
       { "params": [ "X-Position Setpoint" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Position Setpoint" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Position Setpoint" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Main Input Variables",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Main Input Variables",
     "query": "SELECT \"X-Position Current\", \"Y-Position Current\", \"Z-Position Current\" FROM \"Main Input Variables\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "X-Position Current" ], "type": "field" }
      ],
      [
       { "params": [ "Y-Position Current" ], "type": "field" }
      ],
      [
       { "params": [ "Z-Position Current" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}